### ISSUE TITLE
Giving a cookie should emit a message on the Fedora Messaging bus

### ISSUE THREAD

**Issue by abompard** [fedora-infra/maubot-fedora#20]
Idea by @jwflory

**Comment by Conan-Kudo** [comment]
IIRC, old zodbot does this so that cookie badges can be awarded. So we would need this to be able to automatically award cookie badges with new zodbot too, right?

**Comment by mattdm** [comment]
We _definitely_ want badges. This is also a good signal for contributor engagement.
