### ISSUE TITLE
Multiline info not respecting newlines in minutes

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/maubot-fedora#40]
I ran the infra meeting on Matrix last week and noticed that the newlines in multiline info are not respected.

See first line in [minutes from the meeting](https://meetbot.fedoraproject.org/meeting-3_matrix_fedoraproject-org/2023-11-16/infrastructure.2023-11-16-16.00.html).

**Comment by ryanlerch** [comment]
Opened https://github.com/GregSutcliffe/maubot-meetings/issues/43
