### ISSUE TITLE
`!hi`/`!hello` responses should be replies to the command message

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/maubot-fedora#46]
I noticed in a couple of meetings that it becomes somewhat confusing to determine who zodbot's response is to, especially when a bunch of people call `!hi` at the same time. Can we adjust this so that zodbot does each response as a reply to the command so that it's known who zodbot is identifying?

**Comment by Conan-Kudo** [comment]
1. Both interactive and logs.
2. It tagged the user in the response. (ie. "nick: response") This is also an acceptable way to handle this if replies wouldn't work.

**Comment by ryanlerch** [comment]
okay, a little confused here as to the problem you are encountering.

i did a bit of digging, and IRC zodbot does not "reply" for hello commands. the response is:

```
[16:25:33] <ryanlerch> .hello kevin
[16:25:35] <zodbot> kevin 'Kevin Fenzi' <kevin@scrye.com>
```

adding a prefix here is going to confuse things a lot.

e.g.


```
[16:25:33] <ryanlerch> .hello kevin
[16:25:35] <zodbot> ryanlerch: kevin 'Kevin Fenzi' <kevin@scrye.com>
```

```
[16:25:33] <ryanlerch> .hello ryanlerch
[16:25:35] <zodbot> ryanlerch: ryanlerch 'Ryan Lerch' <rlerch@redhat.com>
```

in this context, does it really matter who did the call? isnt the point just kinda like a rollcall?

**Comment by ryanlerch** [comment]
we could in  theory make all zodbot responses replies, but the way element (and other clients too) displays them adds a lot of visual noise when doing it a lot. Each reply repeats the full command. Its just a lot of unneeded noise IMHO.

# With replies (proposed)
![Screenshot from 2023-12-05 16-38-00](https://github.com/fedora-infra/maubot-fedora/assets/592259/634a6030-70e3-4de2-9dae-cd525bbacce9)

# The way it currently is
![Screenshot from 2023-12-05 16-40-43](https://github.com/fedora-infra/maubot-fedora/assets/592259/46fe97ce-5b95-4b4d-9830-b4aa9afc16e0)

**Comment by Conan-Kudo** [comment]
@ryanlerch the problem right now with `hi`/`hello` is that you can't tell who it is _for_. 

For example, if I do `!hi` at the same time as five other people (as is common in FESCo roll call), there's no way to tell which MXID matches up with which person. IRC zodbot handles this by tagging the person who requested it. If we don't want to do replies, then Matrix zodbot should do the same.

**Comment by ryanlerch** [comment]
> IRC zodbot handles this by tagging the person who requested it. 

My point here is IRC zodbot doesn't tag the person who requested it

see comment https://github.com/fedora-infra/maubot-fedora/issues/46#issuecomment-1840092693

**Comment by Conan-Kudo** [comment]
> > IRC zodbot handles this by tagging the person who requested it.
> 
> My point here is IRC zodbot doesn't tag the person who requested it
> 
> see comment [#46 (comment)](https://github.com/fedora-infra/maubot-fedora/issues/46#issuecomment-1840092693)
> 
```
[16:25:33] <ryanlerch> .hello kevin
[16:25:35] <zodbot> ryanlerch: kevin 'Kevin Fenzi' <kevin@scrye.com>
```
This looks like it tagged you, the person who requested the information. That's what I'm talking about.

> Does IRC zodbot respond faster so this is not an issue? Just wondering what has changed here from IRC zodbot to matrix zodbot

Most of the time, yes. But it is actually quite confusing for the general case. As an example, [last week's EPEL meeting logs](https://meetbot.fedoraproject.org/meeting_matrix_fedoraproject-org/2023-11-29/epel.2023-11-29-21.00.log.html), which prompted me to file this issue.
