### ISSUE TITLE
user info help is same as user hello help 

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/maubot-fedora#51]
Obvious copypasta issue.  Just need to fix it.

```
Usage: !user <subcommand> [...]

hello [username] - Return brief information about a Fedora user.
info [username] - Return brief information about a Fedora user.
localtime <username> - Returns the current time of the user.
```

**Comment by NoubissiViany** [comment]
Hi, @ryanlerch  Is this issue still active and up to date? I would like to work on it as an Outreachy intern. Also can I please have more details about the task

**Comment by Precious000** [comment]
Hi @ryanlerch would you mind assigning this issue to me? I would love to work on it. Thanks boss

**Comment by KimFarida** [comment]
@abompard Hello mentor, made a pr concerning this issue. Please could you take a look?
